---
title: "LaborDayTweetsWordCloud"
author: "Anisha BharathSingh"
date: "8/29/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install Packages
```{r}
#install.packages("stringr")
#install.packages("twitteR")
#install.packages("purrr")
#install.packages("tidytext")
#install.packages("dplyr")
#install.packages("tidyr")
#install.packages("lubridate")
#install.packages("scales")
#install.packages("broom")
#install.packages("ggplot2")
```

## Load packages
```{r}
library(stringr)
library(twitteR)
library(purrr)
library(tidytext)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)
library(broom)
library(ggplot2)
```

## Access keys and tokens
```{r}
api_Key = "Insert your API key"
api_Secret = "Insert your Secret API key"
access_Token = "Insert your access token"
access_Token_Secret = "Insert your secret access token"
```


## Setup R and Twitter API Connection
```{r}
options(httr_oauth_cache=TRUE)
setup_twitter_oauth(consumer_key = api_Key, consumer_secret = api_Secret,
access_token = access_Token, access_secret = access_Token_Secret)
```


## Extract tweets for hashtags
```{r}
LaborDay <- searchTwitter("#LaborDay exclude:retweets", n=1000)
LaborDayTweets_df <- tbl_df(map_df(LaborDay, as.data.frame))
write.csv(LaborDayTweets_df, "LaborDayTweets.csv")
head(LaborDayTweets_df)
```

## Packages for Wordcloud
```{r}
#install.packages("tm")
#install.packages("wordcloud")
#install.packages("RColorBrewer")
library(tm) # text mining package with corpus and termdocumentmatrix functions
library(wordcloud) # create word cloud
library(RColorBrewer) #for setting color of word cloud
```

## Extract the text from the tweets in a vector
```{r}
LaborDay_text = sapply(LaborDay, function(x) x$getText())
```

## Create a corpus
```{r}
LaborDay_corpus = Corpus(VectorSource(LaborDay_text))
```

## Create a document term matrix + Text Cleaning
```{r}
tdm = TermDocumentMatrix(LaborDay_corpus,
   control = list(removePunctuation = TRUE, removeNumbers = TRUE, tolower = TRUE))
```


## Obtain words and frequencies
```{r}
# define tdm as matrix
m = as.matrix(tdm)
# get word counts in decreasing order
word_frequency = sort(rowSums(m), decreasing=TRUE) 
# create a data frame with words and their frequencies
LaborDayTweetsFrequency = data.frame(word=names(word_frequency), freq=word_frequency)
```

## Create Word Cloud
```{r}
wordcloud(LaborDayTweetsFrequency$word, LaborDayTweetsFrequency$freq, random.order=FALSE, colors=brewer.pal(8, "Spectral"))
```

## Save the word cloud in a PNG
```{r}
png("LaborDayTweetsWordCloud.png", width=12, height=8, units="in", res=300)
wordcloud(dm$word, dm$freq, random.order=FALSE, colors=brewer.pal(8, "Spectral"))
dev.off()
```

